/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cinemagra_holymoly_cinemagraph_AnimatedGifEncoder */

#ifndef _Included_com_cinemagra_holymoly_cinemagraph_AnimatedGifEncoder
#define _Included_com_cinemagra_holymoly_cinemagraph_AnimatedGifEncoder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_cinemagra_holymoly_cinemagraph_AnimatedGifEncoder_netsize
#define com_cinemagra_holymoly_cinemagraph_AnimatedGifEncoder_netsize 256L
/*
 * Class:     com_cinemagra_holymoly_cinemagraph_AnimatedGifEncoder
 * Method:    getColorTab
 * Signature: ([BII)[I
 */
JNIEXPORT jbyteArray JNICALL Java_com_cinemagra_holymoly_cinemagraph_AnimatedGifEncoder_getColorTab
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_cinemagra_holymoly_cinemagraph_AnimatedGifEncoder
 * Method:    getIndex
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_cinemagra_holymoly_cinemagraph_AnimatedGifEncoder_getIndex
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
